---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://cloudtrends.github.io/"
title: "Hugo Blog Template for GitHub Pages"
canonifyurls: true
...
